CC = g++
CFLAGS = -Wall 
PREFIX = ../..
INCLUDE = -I${PREFIX}/include

##
# Should not need to edit anything below this line
##

gpt: 
	${CC} ${INCLUDE} ${CFLAGS} main.cpp

clean:
	rm -f *.o; rm -f core; rm -f a.out
 

