CC = g++
CFLAGS = -Wall -fopenmp 
PREFIX = ../..
INCLUDE = -I${PREFIX}/include

##
# Should not need to edit anything below this line
##

all: 
	${CC} ${INCLUDE} ${CFLAGS} bucket.cpp

clean:
	rm -f *.o; rm -f core; rm -f a.out
 

