PREFIX = ../..
include ../make.common

check: add remove moved complex 

add:
	$(CC) $(CFLAGS) SimpleAtomic.cpp add_test.cpp 
	$(TEST_EXEC)

remove:
	$(CC) $(CFLAGS) SimpleAtomic.cpp remove_test.cpp 
	$(TEST_EXEC)

moved:
	$(CC) $(CFLAGS) SimpleAtomic.cpp moved_test.cpp 
	$(TEST_EXEC)

complex:
	$(CC) $(CFLAGS) SimpleAtomic.cpp complex_test.cpp 
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
	$(TEST_EXEC)
