/*
 * Copyright (c) 2013, James Nutaro
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 *
 * Bugs, comments, and questions can be sent to nutaro@gmail.com
 */
#ifndef _adevs_models_h_
#define _adevs_models_h_
#include <cstdlib>
#include <list>
#include <memory>
#include <set>
#include "adevs/exception.h"
#include "adevs/time.h"

using namespace std;


namespace adevs {

/*
 * Declare network and atomic model so types can be used as the type of
 * parent in the basic Devs model and for type ID functions.
 */
template <typename X, typename T>
class Simulator;
template <typename X, typename T>
class Schedule;

typedef int pin_t;

template <typename ValueType>
class PinValue {
  public:
    PinValue(pin_t pin, ValueType& value):pin(pin),value(value){}
    PinValue(const PinValue& src) : pin(src.pin),value(src.value) {}
    const PinValue<ValueType>& operator=(const PinValue& src) {
        pin = src.pin;
        value = src.value;
        return *this;
    }
    pin_t pin;
    ValueType value;
};

/*
 * Base type for all atomic DEVS models.
 */
template <typename X, typename T = double>
class Atomic {
  public:
    /// The constructor should place the model into its initial state.
    Atomic()
        : tL(adevs_zero<T>()),
          q_index(0){}  // The Schedule requires this to be zero
    /// Internal transition function.
    virtual void delta_int() = 0;
    /*
     * External transition function.
     * @param e Time elapsed since the last change of state
     * @param xb Input for the model.
     */
    virtual void delta_ext(T e, std::list<PinValue<X>> const &xb) = 0;
    /*
     * Confluent transition function.
     * @param xb Input for the model.
     */
    virtual void delta_conf(std::list<PinValue<X>> const &xb) = 0;
    /*
     * Output function.  Output values should be added to the list yb.
     * @param yb Empty list to be filled with the model's output
     */
    virtual void output_func(std::list<PinValue<X>> &yb) = 0;
    /*
     * Time advance function. adevs_inf<T>() is used for infinity.
     * @return The time to the next internal event
     */
    virtual T ta() = 0;

  private:
    friend class Simulator<X, T>;
    friend class Schedule<X, T>;

    // Time of last event
    T tL, tN;
    // Index in the priority queue
    unsigned int q_index;

    std::list<PinValue<X>> inputs;
    std::list<PinValue<X>> outputs;
};

/*
 * This is a Mealy type atomic model where its output
 * may depend on its input. Mealy machines cannot be
 * connected to other Mealy machines. An exception
 * will be generated by the Simulator if you attempt
 * to do so.
 */


// Clang complains about the output_func declaration.
// Because what we wrote is what we intended, the
// warning is disable just for this class definition.
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Woverloaded-virtual"
#endif

template <typename X, typename T = double>
class MealyAtomic : public Atomic<X, T> {
  public:
    MealyAtomic<X, T>() : Atomic<X, T>() {}
    MealyAtomic<X, T>* typeIsMealyAtomic() { return this; }
    /*
     * Produce output at e < ta(q) in response to xb.
     * This is output preceding an external event.
     */
    virtual void output_func(T e, list<PinValue<X>> const &xb, list<PinValue<X>> &yb) = 0;
    /*
     * Produce output at e = ta(q) in response to xb.
     * This is output preceding a confluent event.
     */
    virtual void output_func(list<PinValue<X>> const &xb, list<PinValue<X>> &yb) = 0;

  private:
    friend class Simulator<X, T>;
};

#ifdef __clang__
#pragma clang diagnostic pop
#endif

}  // namespace adevs

#endif
