#!/usr/bin/tclsh
# This script deletes all svn directories from the current directory down.

set l [split [exec find ./ -name .svn] '\n']

foreach line $l {
   puts "Deleting $line"
   exec rm -rf $line
   }

exit 0
