
MODELICA_OBJS= \
	modelica/math-support/newuob.o \
	modelica/math-support/newuoa.o \
	modelica/math-support/biglag.o \
	modelica/math-support/bigden.o \
	modelica/math-support/update.o \
	modelica/math-support/trsapp.o \
	modelica/math-support/pivot.o 
 
